export const ActionType = {
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    SET_MESSAGE: "SET_MESSAGE",
    CLEAR_MESSAGE: "CLEAR_MESSAGE",
    GET_DISTRICT_SUCCESS: "GET_DISTRICT_SUCCESS",
    GET_DISTRICT_FAIL: "GET_DISTRICT_FAIL",
    GET_STREET_SUCCESS: "GET_STREET_SUCCESS",
    GET_STREET_FAIL: "GET_STREET_FAIL",
}